"""user_roles

Revision ID: 39093b3d8549
Revises: 790ca16ec37b
Create Date: 2017-05-11 21:46:39.076773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39093b3d8549'
down_revision = '790ca16ec37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
